version: "3.9"

services:
  upi_db:
    image: postgres:15
    container_name: upi_postgres
    volumes:
      - ~/.pg/pg_data/upi:/var/lib/postgresql/data
    env_file:
      - .env
  upi_project:
    build: #we will need this one in case if we did build our docker file previously
      dockerfile: Dockerfile
      context: .
    #image: up1:latest
    container_name: elastic_villan #should take it from docker ps
    depends_on:
      - upi_db #it wont work untill out db will launch
    volumes:
      - static_volume:/upi/static
      - media_volume:/upi/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 upi.wsgi:"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: upi_nginx
    image: upi_nginx
    volumes:
      - static_volume:/yt/static
      - media_volume:/yt/media
    depends_on:
      - upi_project
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"



#we telling docker to figure out sorage palce by it own unlike voulms for upi_db
volumes:
  static_volume:
  media_volume: