# Generated by Django 4.1.3 on 2022-12-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_alter_useraccount_phone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='bank_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
