# Generated by Django 4.1.3 on 2023-01-01 13:28

import base.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_rename_phone_id_useraccount_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_passport',
            field=models.ImageField(blank=True, null=True, upload_to=base.services.get_path_upload_avatar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), base.services.validate_size_image]),
        ),
    ]
