# Generated by Django 4.1.3 on 2022-12-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0012_useraccount_account_type_useraccount_bank_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_id', models.CharField(blank=True, max_length=50, null=True)),
                ('merchat_name', models.CharField(max_length=200)),
                ('merchant_description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.useraccount')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.language')),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.merchantcategory'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='lang_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.language'),
        ),
    ]
