# Generated by Django 4.1.3 on 2022-12-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
