# Generated by Django 4.1.3 on 2022-12-23 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_id', models.CharField(max_length=50)),
                ('merchat_name_ru', models.CharField(max_length=200)),
                ('merchat_name_eng', models.CharField(max_length=150)),
                ('merchant_description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.language')),
            ],
        ),
    ]
