# Generated by Django 4.1.3 on 2022-12-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_banklogos_language_merchantcategory_merchant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='partner_transaction_id',
        ),
    ]
