# Generated by Django 4.1.3 on 2023-01-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_merchantcategory_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='cat_id',
            new_name='merch_cat_id',
        ),
    ]
