# Generated by Django 4.1.3 on 2022-12-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_languages_merchants'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='languages',
            old_name='lang_desc',
            new_name='lang_name',
        ),
    ]
