# Generated by Django 4.1.3 on 2023-01-08 11:00

import base.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_merchantcategory_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_logo',
            field=models.ImageField(blank=True, null=True, upload_to=base.services.get_path_upload_merchant, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), base.services.validate_size_image]),
        ),
    ]
