# Generated by Django 4.1.3 on 2023-01-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_merchant_merchant_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='cat_id',
            new_name='merch_cat_id',
        ),
    ]
