# Generated by Django 4.1.3 on 2022-12-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_transaction_id_transaction_partner_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='merchat_name_ru',
            new_name='merchat_name',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='merchat_name_eng',
        ),
        migrations.AddField(
            model_name='merchant',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.merchantcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantcategory',
            name='categoty_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantcategory',
            name='lang_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.merchant'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='partner_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
