# Generated by Django 4.1.3 on 2023-01-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_cat_id_merchant_merch_cat_id'),
        ('transactions', '0005_rename_cat_id_merchant_merch_cat_id'),
    ]

    operations = [
    ]
