# Generated by Django 4.1.3 on 2023-01-02 17:38

import base.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantcategory',
            name='category_logo',
            field=models.ImageField(blank=True, null=True, upload_to=base.services.get_path_upload_merchant, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), base.services.validate_size_image]),
        ),
    ]
