# Generated by Django 4.1.3 on 2023-03-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantcategory',
            options={'verbose_name_plural': 'Merchant Categories'},
        ),
    ]
