# Generated by Django 4.1.3 on 2023-01-02 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_merchantcategory_category_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantcategory',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2999, 12, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='merchantcategory',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
