# Generated by Django 4.1.3 on 2023-01-15 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_cat_id_merchant_merch_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2999, 12, 1, 0, 0)),
        ),
    ]
