# Generated by Django 4.1.3 on 2023-01-15 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_merchant_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantcategory',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2999, 12, 12, 0, 0)),
        ),
    ]
