# Generated by Django 4.1.3 on 2022-11-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_useraccoutn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccoutn',
            new_name='UserAccount',
        ),
    ]
