# Generated by Django 4.1.3 on 2023-01-01 13:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0013_upiuser_approved_upiuser_user_inn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='phone_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='upiuser',
            name='user_inn',
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_inn', models.CharField(max_length=50, unique=True)),
                ('user_passport', models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
